---
preview: Конструкция *try...catch* помечает блок инструкций как try, и в зависимости от того, произошла ошибка или нет, вызывает дополнительный блок инструкций catch.
title: Errors
tags: js, error, try...catch, -----post-locked-by:yemelyanow-ross
author: yemelyanow-ross
date: 2017-11-26 20:05:00
---

```
class MyError extends Error {
  constructor(message) {
    super(message);
    this.message = message;
    this.name = 'MyError';
  }
}
```

	**Range Error** - данное исключение выбрасывается при попытке передать аргументом в функцию число, которое не входит в допустимый диапазон значений аргумента этой функции. Также оно может возникать при создании массива с неправильной длиной через конструктор Array, или при передаче плохих значений в методы числа Number.toExponential(), Number.toFixed() или Number.toPrecision().
	
	**Reference Error** -  данное исключение выбрасывается при попытке обратиться к переменной, которая не была объявлена.
	
	**Syntax Error** - представляет ошибку, возникающую при попытке интерпретировать синтаксически неправильный код. 
	
	**Type Error** -  данное исключение выбрасывается, когда операнд или аргумент, переданный в функцию, не совместим с типом, ожидаемым оператором или функцией.